# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d08d4c15e3199654da4c2e902d521409ff0a10beea7d439928bd629dcde7332bc5346d8e708679e5864fd4a4876c3ef487be57ea5da68411374cd8ca47d2800

test:
  secret_key_base: 95cc5a069370253c3b6fd6e9f34d20d4dfde39fb33d89dcaaebc3a42d907cf9fd336411002de0dd0b1084ea74e7736f37d21d3867f8769390cff077ff5a1c219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
